### ISSUE TITLE
Omega2+ fails to flash firmware from USB storage

### ISSUE THREAD

**Issue by jithware** [OnionIoT/omega2-bootloader#4]
#### Issue description
Omega2+ fails to flash firmware from USB storage

#### Steps to reproduce the issue
Follow usb flashing procedure: https://docs.onion.io/omega2-docs/Firmware-Flashing-from-USB-storage.html
Use image: http://repo.onioniot.com.s3.amazonaws.com/omega2/images/omega2p-v0.3.2-b233.bin

#### What's the expected result?
New firmware is flashed to device.

#### What's the actual result?
*ERROR: CTL:TIMEOUT X
BBB_reset
usb_control_msg: request: 0xFF, requesttype: 0x21
value 0x0 index 0x0 length 0x0
ERROR: CTL:TIMEOUT X

#### Additional details / screenshot
![screenshot](https://user-images.githubusercontent.com/30555367/74680716-7b5bac00-518f-11ea-8b9c-5775faa56919.png)

**Comment by greenbreakfast** [comment]
Yes, this is a known issue.  When trying to use USB storage to flash a firmware image that is greater than ~8 MB, the USB transfer times out.

Is there a smaller image you can try flashing?

Also, which version of the bootloader are you running? To get the version number, enter the bootloader and enable the command prompt. The compile date will tell you the version.

**Comment by greenbreakfast** [comment]
@jithware Try out the latest `2020-05-12` release of the bootloader. **It has a fix for USB storage firmware flashing.**

Instructions on flashing a new bootloader to Omega2 device can be found here: http://docs.onion.io/omega2-docs/Web-Recovery-flash-bootloader.html

Let us know how it goes!

**Comment by jithware** [comment]
Unfortunately I have the Mini Dock and it does not have an Ethernet port.  Is there another way to flash the bootloader without using the web recovery? Or rig and Ethernet port to the Mini Dock?

**Comment by greenbreakfast** [comment]
@jithware you can try rigging it, but you'll get the best results if you use a Dock that supports the Ethernet Expansion

**Comment by QB4-dev** [comment]
@greenbreakfast Hello, same situation as above - cannot flash firmware from USB.
`Onion Omega2 UBoot Version: 4.3.0.3`

I was trying to build and flash custom firmware from official repo: https://github.com/OnionIoT/source
It produces default image file with size(7602354 bytes):
openwrt-ramips-mt76x8-omega2p-squashfs-sysupgrade.bin

> When trying to use USB storage to flash a firmware image that is greater than ~8 MB, the USB transfer times out.

I still have USB timeout error: `ERROR: CTL:TIMEOUT X' despite fimware image size is less than 8MB

I don't have ethernet expansion board. Is there any way to bring the board back to life?
Mayby by booting device from USB stick and then replace bootloader to the fixed one?


EDIT: I've soldered ethernet socket directly to minidock ethernet pins and then updated u-boot, everything works again

**Comment by greenbreakfast** [comment]
@QB4-dev Glad it worked out! 

Yep, u-boot version 2020-05-12 fixes the flashing from USB issue
